version: 2
jobs:
  build:
    docker:
      - image: trichards/permfixer
    steps:
      - checkout
      - run:
          name: Compile application
          command: make dist
      - store_artifacts:
          path: permfixer
          destination: permfixer
