version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stable
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo apt-get -y install libacl1-dev
      - run:
          name: Compile application
          command: make dist
      - store_artifacts:
          path: permfixer
          destination: permfixer
